name: Test this action

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs: 
  test:
    name: Run example mirroring
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: this
      - name: Mirror wearerequired/git-mirror-action to morbalint/git-mirror-action
        uses: ./this/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          # SSH_KNOWN_HOSTS is a result of `ssh-keyscan github.com` with manually added \n 
          # Please update if GitHub changes keys 
          SSH_KNOWN_HOSTS: "# github.com:22 SSH-2.0-babeld-0f6ba948\n
            github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=\n
            # github.com:22 SSH-2.0-babeld-0f6ba948\n
            github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==\n
            # github.com:22 SSH-2.0-babeld-0f6ba948\n
            github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl"\n
        with:
          source-repo: "https://github.com/wearerequired/git-mirror-action.git" # Proof that HTTPS works as well
          destination-repo: "git@github.com:morbalint/git-mirror-action.git"
          dry-run: true
        